/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MemoryEntry {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'createdAt' : bigint,
  'photoIds' : Array<string>,
  'narrative' : string,
  'location' : string,
}
export interface NewMemoryInput {
  'title' : string,
  'date' : string,
  'photoIds' : Array<string>,
  'narrative' : string,
  'location' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'profilePicture' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMemory' : ActorMethod<[NewMemoryInput], bigint>,
  'deleteMemory' : ActorMethod<[bigint], undefined>,
  'getAllMemories' : ActorMethod<[], Array<MemoryEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMemoriesByLocation' : ActorMethod<[string], Array<MemoryEntry>>,
  'getMemoriesByYear' : ActorMethod<[bigint], Array<MemoryEntry>>,
  'getMemoriesCount' : ActorMethod<[], bigint>,
  'getMemory' : ActorMethod<[bigint], MemoryEntry>,
  'getOnThisDayMemories' : ActorMethod<[bigint, bigint], Array<MemoryEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMemoryStoreEmpty' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMemories' : ActorMethod<[string], Array<MemoryEntry>>,
  'updateMemory' : ActorMethod<[bigint, NewMemoryInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];